services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    restart: unless-stopped

  firehose:
    image: ${IMAGE_NAME}:${APP_VERSION}-firehose
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    depends_on:
      - clickhouse
    volumes:
      - ./cursor.txt:/app/cursor.txt
    restart: unless-stopped

  webapp:
    image: ${IMAGE_NAME}:${APP_VERSION}-webapp
    build:
      context: .
      dockerfile: webapp.Dockerfile
    expose:
      - "8000"
    environment:
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
    depends_on:
      - clickhouse
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./bluehoover/dashboard/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - webapp
    restart: unless-stopped

volumes:
  clickhouse_data:
